name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update packages repository
        run: |
          sudo apt-get update

      - name: Install libyaml-libyaml-perl
        run: |
          sudo apt-get install libyaml-libyaml-perl

      - name: Install debdiff for debtransform test
        run: |
          sudo apt-get install devscripts

      - name: Test
        run: |
          make test test-debtransform
